### ISSUE TITLE
WARNING

### ISSUE THREAD

**Issue by adamsky-01** [parotic0/NSTool#3]
...and what this nice string is doing in your code:
`https://discordapp.com/api/v6/users/@me/billing/payment-sources`

**Comment by parotic0** [comment]
the other guy working on the project added that as a way to check if the discord was authenticated, You can look at the code. 
we just send a request and check if it's valid we dont collect any information, store it, or even see anything. we dont interact with the information on the page. also as you can see our code doesn't interact with any other online services other than twitter/discord.

**Comment by adamsky-01** [comment]
It's parts of NitroHack malware

**Comment by parotic0** [comment]
its not, please know what your talking about before you start throwing accusations.
i will explain literally everything the code does

** headers are set and auth token are set **

** a GET request is sent to the URL with headers with nothing being stored
response = requests.get('https://discordapp.com/api/v6/users/@me/billing/payment-sources', headers=headers)

** response.ok checks if the request went through without any problems, return either says true or false depending on if the request was valid
return response.ok

please don't accuse me of stuff like this, i just want to share something cool i made.

**Comment by ghost** [comment]
> It's parts of NitroHack malware

What are you even on about? You have the entire source of the project; if you don't trust something manually verify the code? It's not that hard. It's not networked to anything but the Discord server. 

Start reading.
